name: build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.17.1"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: build app
        run: yarn build && touch out/.nojekyll
      - name: deploy app
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
